### ISSUE TITLE
dates not getting updated?

### ISSUE THREAD

**Issue by fmmattioni** [dreamRs/tuicalendr#14]
Hey @pvictor,

While trying to check the selection of dates from the server side, I have noticed that `_dates` does not update when clicking the previous and next buttons?

reprex:

```r
library(tuicalendr)
library(shiny)

# App ----
ui <- fluidPage(
  calendarOutput(outputId = "cal")
)

server <- function(input, output, session) {
  output$cal <- renderCalendar({
    calendar(defaultView = "month", useNav = TRUE, taskView = TRUE, scheduleView = c("time", "allday"))
  })
  
  observeEvent(input$cal_prev, {
    print(input$cal_dates)
  })
}

shinyApp(ui, server)
```

**Comment by pvictor** [comment]
Yep that's a bug, it's fixed.

Can I ask in which context do you use this package ? I'm currently re-writing this widget into another package (with little changes in API), so this package won't evolve much, the new one is intended to be published on the CRAN. It isn't public yet, but I can give you access

**Comment by fmmattioni** [comment]
Oh, that would be awesome!!

I am using it in a shiny app. Basically, once the user logs in, a GET request is sent to an API, which is where I get the `schedules` from. This API has a limit of 45 days from the `start` to `end` date. So, basically, every time the user navigates into the calendar, a new request is sent, and new (if any) schedules are populated into the calendar.

Let me know if that makes sense.

Felipe
