### ISSUE TITLE
shiny app, calendar is skipping days when it includes dynamic input

### ISSUE THREAD

**Issue by Psqrt** [dreamRs/tuicalendr#2]
Hello,

I've encountered a weird behiavior from my calendar when I use it in a Shiny app with dynamic input.

Here's a reprex :

```
library(shiny)
library(shinyWidgets)
library(tuicalendr)
library(dplyr)


ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(
            pickerInput("filter_id",
                        label = "Filter",
                        selected = "id1",
                        choices = c("id1", "id2")
            )
        ),
        mainPanel(
            calendarOutput("agenda")
        )
    )
)

server <- function(input, output) {
    
    output$agenda <- renderCalendar({
        
        calendarProps <- data.frame(
            id = c("1"), 
            name = c("test"),
            color = c("#000000"), 
            bgColor = c("#fcba03"),
            borderColor = c("#fcba03")
        )
        
        # useless data for example
        df = data.frame("id" = c("id1", "id2"),
                        "calendarId" = rep(1, 2),
                        "title" = rep("title1", 2),
                        "start" = rep(Sys.time(), 2),
                        "end" = rep(Sys.time() + 60 * 60 * 2, 2),
                        "category" = rep("time", 2)
        )
        
        df = df %>% 
            filter(id == input$filter_id)
        
        calendar(defaultView = "week",
                 taskView = F,
                 scheduleView = "time",
                 useNav = T) %>% 
            set_calendars_props_df(calendarProps) %>% 
            add_schedule_df(df)
    })
}

shinyApp(ui = ui, server = server)
```

When you're in the app, select "id2" in the pickerInput then start navigating between weeks, you will notice that some days are skipped.

Thanks!

**Comment by pvictor** [comment]
Salut,

Thanks for reporting this and for the example 👍 , this should be fixed.

Victor

**Comment by Psqrt** [comment]
Salut,

Thanks for the fast answer. It looks like the correct way to update the calendar is to use `calendarProxy()` and `cal_proxy_...()` functions (the same way as leaflet R package), but I could only create one task at the time with `cal_proxy_create()`. Is there an equivalent to `add_schedule_df` for proxy? My goal is to get every line from a filtered dataframe (according to the pickerInput selected value) to the calendar.

**Comment by Psqrt** [comment]
Salut,

Indeed, it's working fine now. Thanks for the fast answer!

**Comment by pvictor** [comment]
Cool!
For the other question please open an issue, for now you cannot add a `data.frame`, but something like a `for` loop, but i think I can add a new function.
