### ISSUE TITLE
Unable to delete schedules in edit example

### ISSUE THREAD

**Issue by josho88** [dreamRs/tuicalendr#4]
Hello. The edit schedules example is great and exactly what I need. However, I don't seem to be able to figure out how to delete a schedule using the proxy method? It doesn't seem to be covered in the example. Have tried using 'input$my_calendar_delete' in conjunction with cal_proxy_delete but can't seem to make progress. Any ideas if this is possible? Thanks!

**Comment by pvictor** [comment]
Hello,
I forgot to add a special input when delete button is clicked, that's fixed, I updated the example here (you'll need to reinstall from GitHub) : https://github.com/dreamRs/tuicalendr/blob/master/inst/proxy-examples/edit-schedule-interactive.R

There's still some documentation to write 🙃 , I hope you get to do what you want.

Victor

**Comment by josho88** [comment]
@pvictor that's perfect, thanks for the swift response!
