### ISSUE TITLE
How to enable copy on event popup

### ISSUE THREAD

**Issue by sebastiz** [dreamRs/tuicalendr#6]
is it possible to select text from the pop-up box when a calendar event is clicked? There is text I would like to highlight and copy but this seems to be disabled.

**Comment by pvictor** [comment]
Hello,
Yes this was disabled, only available in latest JS lib release, the package is now up to date, please re-install from GitHub, this should work.

Victor

**Comment by sebastiz** [comment]
Thanks that worked really nicely
